# Name of your application. Used to uniquely configure containers.
service: cloacker

# Name of the container image.
image: celipi/cloacker

# Deploy to these servers.
servers:
  web:
    - 5.161.244.20
  # job:
  #   hosts:
  #     - 192.168.0.1
  #   cmd: bin/jobs

# Enable SSL auto certification via Let's Encrypt (and allow for multiple apps on one server).
# If using something like Cloudflare, it is recommended to set encryption mode 
# in Cloudflare's SSL/TLS setting to "Full" to enable end-to-end encryption. 
proxy: 
  ssl: true
  host: cloacker.evosync.com.br
  # kamal-proxy connects to your container over port 80, use `app_port` to specify a different port.
  app_port: 3000
  healthcheck:
    path: /up
    interval: 5
    timeout: 3

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  server: ghcr.io
  username: celipi

  # Always use an access token rather than real password (pulled from .kamal/secrets).
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64

env:
  clear:
    DB_HOST: postgres
    POSTGRES_USER: postgres
    DB_PORT: "5432"
    POSTGRES_DB: cloacker
  secret:
    - POSTGRES_PASSWORD

accessories:
  postgres:
    image: postgres:15
    host: 5.161.244.20  # Or use roles: [web] 
    env:
      clear:
        POSTGRES_USER: postgres
        POSTGRES_DB: cloacker
      secret:
        - POSTGRES_PASSWORD
    files:
      - config/init.sql:/docker-entrypoint-initdb.d/setup.sql 
    directories:
      - data:/var/lib/postgresql/data 
